jobs:
  - template: ./ci/ios-e2e-template.yml
    parameters:
      name: e2e_basic_12
      script: |
        npm install --no-save mjpeg-consumer
        npx mocha --timeout 480000 --reporter mocha-junit-reporter --recursive build/test/functional/basic -g @skip-ci -i --exit

  - template: ./ci/ios-e2e-template.yml
    parameters:
      name: e2e_driver_12
      script: npx mocha --timeout 480000 --reporter mocha-junit-reporter --recursive build/test/functional/driver -g @skip-ci -i --exit

  - template: ./ci/ios-e2e-template.yml 
    parameters:
      name: e2e_web_12
      script: npx mocha --timeout 480000 --reporter mocha-junit-reporter --recursive build/test/functional/web -g @skip-ci -i --exit

  - template: ./ci/ios-e2e-template.yml
    parameters:
      name: e2e_long_12
      script: npx mocha --timeout 480000 --reporter mocha-junit-reporter --recursive build/test/functional/long -g @skip-ci -i --exit

  
